# Generated by Django 4.1 on 2024-09-01 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('platform', models.CharField(choices=[('TG', 'Telegram'), ('BALE', 'Bale')], default='BALE', max_length=10)),
                ('id', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('user_id', models.PositiveBigIntegerField(null=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.IntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('inviter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitee', to='user.user')),
            ],
            options={
                'unique_together': {('platform', 'user_id')},
            },
        ),
    ]
