# Generated by Django 4.1 on 2024-09-01 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_male',
            field=models.BooleanField(default=True),
        ),
    ]
